src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table('user')]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'user_type', type: 'string')]
#[ORM\DiscriminatorMap([
    'user' => User::class,
    'website_user' => WebsiteUser::class,
    'company_user' => CompanyUser::class,
])]
abstract class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 125)]
    private ?string $lastname = null;

    #[ORM\Column(length: 125)]
    private ?string $firstname = null;

    #[ORM\Column(length: 125)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $isVerified = false;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                    <div class="card-body">
                        <form method="post">
                            {% if error %}
                                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                            {% endif %}

                            {% if app.user %}
                                <div class="mb-3">
                                    You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                                </div>
                            {% endif %}

                            <div class="form-floating mb-3">
                                <input type="text" value="{{ last_username }}" name="username" id="inputUsername"
                                       class="form-control"
                                       autocomplete="username" required autofocus
                                       placeholder="Pseudo">
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" name="password" id="inputPassword" class="form-control"
                                       autocomplete="current-password"
                                       required>
                            </div>

                            <input type="hidden" name="_csrf_token"
                                   value="{{ csrf_token('authenticate') }}"
                            >


                            {#
                            Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                            See https://symfony.com/doc/current/security/remember_me.html

                            <div class="checkbox mb-3">
                                <label>
                                    <input type="checkbox" name="_remember_me"> Remember me
                                </label>
                            </div>
                            #}

                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="{{ path('home_reset_password') }}">Forgot Password?</a>
                                <button class="btn btn-lg btn-primary" type="submit">
                                    Sign in
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center py-3">
                        <div class="small"><a href="{{ path('company_register') }}">Need an account? Sign up!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/security/register.html.twig
{% extends "base.html.twig" %}

{% block title %}Register{% endblock %}

{% block body %}
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ path('app_home') }}">Home</a></li>
        <li class="breadcrumb-item active">Register as company</li>
    </ol>

    <h1 class="mt-4">Register as company</h1>

    {{ form_start(form) }}

    <legend>Company</legend>
    <div class="row mb-3">
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.name) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.logo) }}
            </div>
        </div>

        <div class="col-md-2">
            <div class="form-floating">
                {{ form_row(form.color) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.location) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.website) }}
            </div>
        </div>
    </div>

    <legend>Contact Company</legend>
    <div class="row mb-3">
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.lastname) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.firstname) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.email) }}
            </div>
        </div>
    </div>

    <legend>Identifiant</legend>
    <div class="row mb-3">
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.username) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-floating">
                {{ form_row(form.password) }}
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

    {{ form_end(form) }}

    {% if is_granted("ROLE_USER") == false %}
        <a href="{{ path('app_login') }}" class="btn btn-outline-info">Login</a>
    {% endif %}

{% endblock %}